### ISSUE TITLE
Refactor "hardcoded" forms in templates/Account to use Crispy

### ISSUE THREAD

**Issue by magnuhar** [wemadefree/WeBook#20]
It would be desirable to refactor the hardcoded forms, introduced by PR #19, into the more brief Crispy way. 

All of those forms should be (ideally) replaced with: 
`{{ form | crispy }}`

To achieve this we need to remedy the issue that caused it to be done like this in the first place. We need to create our own template fields, and get these fields into these forms.

**Comment by eivl** [comment]
yes, agreed, its an important change. Crispy forms are installed for this exact use case. I would solve this sooner rather then later to just be done with it.
